### PR TITLE
Fix Clippy Warnings

### LINKED ISSUE #378: Clippy Warnings in `tarpc`
# Clippy Warnings

Currently `master` branch contains the following warnings : 
- Needless-borrow
- redundant_field_names
- field_reassign_with_default
- bool_assert_comparison
- derive_partial_eq_without_eq

## Suggestion

Fix all suggested warnings to maintain `clippy` standards.

### PR DESCRIPTION
**Pull request by royrustdev**
# Fixed Following Cippy Warnings

- Needless-borrow
- redundant_field_names
- field_reassign_with_default
- bool_assert_comparison
- derive_partial_eq_without_eq

Fixes #378

### CODE REVIEW

File: tarpc/src/server.rs [hunk 1]
```diff
@@ -837,7 +837,9 @@ mod tests {
         channel::Channel<Response<Resp>, ClientMessage<Req>>,
     ) {
         let (tx, rx) = crate::transport::channel::bounded(capacity);
-        let mut config = Config::default();
+        let mut config = Config {
+            pending_response_buffer: capacity + 1,
+        };
         // Add 1 because capacity 0 is not supported (but is supported by transport::channel::bounded).
```
Comment (tikue) [inline tarpc/src/server.rs:843]: Nit: move this comment up

File: tarpc/src/server.rs [hunk 2]
```diff
@@ -837,7 +837,9 @@ mod tests {
...
         config.pending_response_buffer = capacity + 1;
```
Comment (tikue) [inline tarpc/src/server.rs:844]: Nit: this line is superfluous, right?

**Review by tikue — CHANGES_REQUESTED** [review]
Thanks! Just a couple minor things.

File: tarpc/src/server.rs (hunk 1 above)
Comment (royrustdev) [reply tarpc/src/server.rs:843]: Ok

File: tarpc/src/server.rs (hunk 2 above)
Comment (royrustdev) [reply tarpc/src/server.rs:844]: Sorry. My mistake.

**Review by tikue — APPROVED** [review]

**Comment by tikue** [comment]
Thanks!
